In [1]:
%%html
<marquee style='width: 30%; color: blue;'><b>Hello Matrix!</b></marquee>

Matrix: Colunms go down and rows go side ways
$$
b=\begin{bmatrix}
0 & 1 & 2 \\
-3 & 4 & -5 
\end{bmatrix}
$$
There are 3 columns and 2 rows in this matrix

NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original. The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.          

In [2]:
import numpy as np # import numpy
import matplotlib.pyplot as plt # import matplotlib for plotting graphs

%matplotlib notebook
plt.rcParams['figure.figsize'] = [10, 6] # configuring graph size

In [3]:
print("simple 6x7 matrix")
a = np.arange(42).reshape(6, 7)
print('a=', a)
print('dimension of matrix=', a.shape)

simple 6x7 matrix
a= [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]
dimension of matrix= (6, 7)


In [4]:
print("access matrix rows")
print("a[0] =", a[0]) # First Row
print("a[2] =", a[3]) # Third Row
print("a[-1] =", a[-1]) # Last Row (3rd row in this case)

access matrix rows
a[0] = [0 1 2 3 4 5 6]
a[2] = [21 22 23 24 25 26 27]
a[-1] = [35 36 37 38 39 40 41]


In [5]:
print("access matrix columns")
print("a[:,0] =",a[:,0]) # First Column
print("a[:,3] =", a[:,5]) # Fourth Column
print("a[:,-1] =", a[:,-1]) # Last Column (4th column in this case)

access matrix columns
a[:,0] = [ 0  7 14 21 28 35]
a[:,3] = [ 5 12 19 26 33 40]
a[:,-1] = [ 6 13 20 27 34 41]


In [6]:
print("slicing a matrix")
print("a[:,2:5] =",a[:,0]) # All rows, third to the fifth column

slicing a matrix
a[:,2:5] = [ 0  7 14 21 28 35]


In [7]:
print("simple 2x3 matrix with float elements")
b = np.array([[1.1, 2, 3], [3, 4, 5]]) # Array of floats
print('b=', b)

simple 2x3 matrix with float elements
b= [[1.1 2.  3. ]
 [3.  4.  5. ]]


In [8]:
print("simple 2x3 matrix with complex elements")
c = np.array([[1, 2, 3], [3, 4, 5]], dtype = complex) # Array of complex numbers
print('c=', c)

simple 2x3 matrix with complex elements
c= [[1.+0.j 2.+0.j 3.+0.j]
 [3.+0.j 4.+0.j 5.+0.j]]


In [9]:
print("reshaping an array dimension")
d = b.reshape(3,2)
print('d=', d)
print('dimension of matrix=', d.shape)

reshaping an array dimension
d= [[1.1 2. ]
 [3.  3. ]
 [4.  5. ]]
dimension of matrix= (3, 2)


In [10]:
print("resize an array dimension")
e = np.resize(b,(4,4))
print('e =', e)
print('dimension of matrix=', e.shape)

resize an array dimension
e = [[1.1 2.  3.  3. ]
 [4.  5.  1.1 2. ]
 [3.  3.  4.  5. ]
 [1.1 2.  3.  3. ]]
dimension of matrix= (4, 4)


In [11]:
print("matrix addition")
f = np.array([[2, 4], [5, -6]])
g = np.array([[9, -3], [3, 6]])
h = f + g
print('h =', h)

matrix addition
h = [[11  1]
 [ 8  0]]


In [12]:
print("matrix transpose")
i = h.transpose()
print('i =', i)

matrix transpose
i = [[11  8]
 [ 1  0]]


In [13]:
print("matrix multiplication")
j = h.dot(i)
print('j =', j)

matrix multiplication
j = [[122  88]
 [ 88  64]]


In [14]:
print("matrix multiplication")
k = np.cross(h, i)
print('k =', k)

matrix multiplication
k = [77  0]


Bad pipe message: %s [b'\x11n\xce\x9d\x19]\xad\xe9\x13F{\x18\xe5F\xae\x92\xc5Z ;\t\xf5\xecX5\xf1c\xd0}w\xe7\xccY\xbbo\xfb\xa90T\xf0\x9c5\x9cd\xf2\xe5\xc1\xfd\xf4F.\x00\x08\x13\x02\x13\x03\x13\x01\x00\xff\x01\x00\x00\x8f\x00\x00\x00\x0e\x00\x0c\x00\x00\t127.0.0.1\x00\x0b\x00\x04\x03\x00\x01\x02\x00\n\x00\x0c\x00\n\x00\x1d\x00\x17\x00\x1e\x00\x19\x00\x18\x00#\x00\x00\x00\x16\x00\x00\x00\x17\x00\x00\x00\r\x00\x1e\x00\x1c\x04\x03\x05\x03\x06\x03\x08\x07\x08\x08\x08\t\x08\n\x08\x0b\x08\x04\x08\x05\x08\x06\x04\x01\x05\x01\x06\x01\x00+\x00\x03\x02\x03\x04\x00-\x00\x02\x01\x01\x003\x00&\x00$\x00\x1d']
Bad pipe message: %s [b'\xce\xa8l\x819\x11\xe1\xceF\xe9\xc3l5,\xe2O\xe2\xfc \xcfY?\x0cS\xe8S)\xe8\x0e\xcd\x1b\xdeYL~Pfp\t\xde\xbdh\x08"\xf6K\xd7\x1buS\xc0\x00\x08\x13\x02\x13\x03\x13\x01\x00\xff\x01\x00\x00\x8f\x00\x00\x00\x0e\x00\x0c\x00\x00\t127.0.0.1\x00\x0b\x00\x04\x03\x00\x01\x02\x00\n\x00\x0c\x00\n\x00\x1d\x00\x17\x00\x1e\x00\x19\x00\x18\x00#\x00\x00\x00\x16\x00\x00\x00\x17\x00\x00\x00\r\x0